// Generated by scripts/generate-register-components.ts — do not edit.

/** Register `pk-button` only (async side-effect import). */
export async function registerPkButton(): Promise<void> {
    await import('./components/button/pk-button.js');
}

/** Register `pk-button-group` only (async side-effect import). */
export async function registerPkButtonGroup(): Promise<void> {
    await import('./components/button-group/pk-button-group.js');
}

/** Register `pk-button-group-separator` only (async side-effect import). */
export async function registerPkButtonGroupSeparator(): Promise<void> {
    await import('./components/button-group/pk-button-group-separator.js');
}

/** Register `pk-button-group-text` only (async side-effect import). */
export async function registerPkButtonGroupText(): Promise<void> {
    await import('./components/button-group/pk-button-group-text.js');
}

/** Register `pk-calendar` only (async side-effect import). */
export async function registerPkCalendar(): Promise<void> {
    await import('./components/calendar/pk-calendar.js');
}

/** Register `pk-checkbox` only (async side-effect import). */
export async function registerPkCheckbox(): Promise<void> {
    await import('./components/checkbox/pk-checkbox.js');
}

/** Register `pk-checkbox-select` only (async side-effect import). */
export async function registerPkCheckboxSelect(): Promise<void> {
    await import('./components/checkbox-select/pk-checkbox-select.js');
}

/** Register `pk-code-editor` only (async side-effect import). */
export async function registerPkCodeEditor(): Promise<void> {
    await import('./components/code-editor/pk-code-editor.js');
}

/** Register `pk-color-input` only (async side-effect import). */
export async function registerPkColorInput(): Promise<void> {
    await import('./components/color-input/pk-color-input.js');
}

/** Register `pk-combobox` only (async side-effect import). */
export async function registerPkCombobox(): Promise<void> {
    await import('./components/combobox/pk-combobox.js');
}

/** Register `pk-copy-button` only (async side-effect import). */
export async function registerPkCopyButton(): Promise<void> {
    await import('./components/copy-button/pk-copy-button.js');
}

/** Register `pk-date-picker` only (async side-effect import). */
export async function registerPkDatePicker(): Promise<void> {
    await import('./components/date-picker/pk-date-picker.js');
}

/** Register `pk-dialog` only (async side-effect import). */
export async function registerPkDialog(): Promise<void> {
    await import('./components/dialog/pk-dialog.js');
}

/** Register `pk-dropdown-item` only (async side-effect import). */
export async function registerPkDropdownItem(): Promise<void> {
    await import('./components/dropdown-menu/pk-dropdown-item.js');
}

/** Register `pk-dropdown-label` only (async side-effect import). */
export async function registerPkDropdownLabel(): Promise<void> {
    await import('./components/dropdown-menu/pk-dropdown-label.js');
}

/** Register `pk-dropdown-menu` only (async side-effect import). */
export async function registerPkDropdownMenu(): Promise<void> {
    await import('./components/dropdown-menu/pk-dropdown-menu.js');
}

/** Register `pk-dropdown-separator` only (async side-effect import). */
export async function registerPkDropdownSeparator(): Promise<void> {
    await import('./components/dropdown-menu/pk-dropdown-separator.js');
}

/** Register `pk-editable-table` only (async side-effect import). */
export async function registerPkEditableTable(): Promise<void> {
    await import('./components/editable-table/pk-editable-table.js');
}

/** Register `pk-field` only (async side-effect import). */
export async function registerPkField(): Promise<void> {
    await import('./components/field/pk-field.js');
}

/** Register `pk-icon` only (async side-effect import). */
export async function registerPkIcon(): Promise<void> {
    await import('./components/icon/pk-icon.js');
}

/** Register `pk-input` only (async side-effect import). */
export async function registerPkInput(): Promise<void> {
    await import('./components/input/pk-input.js');
}

/** Register `pk-input-group` only (async side-effect import). */
export async function registerPkInputGroup(): Promise<void> {
    await import('./components/input-group/pk-input-group.js');
}

/** Register `pk-input-group-addon` only (async side-effect import). */
export async function registerPkInputGroupAddon(): Promise<void> {
    await import('./components/input-group/pk-input-group-addon.js');
}

/** Register `pk-input-group-button` only (async side-effect import). */
export async function registerPkInputGroupButton(): Promise<void> {
    await import('./components/input-group/pk-input-group-button.js');
}

/** Register `pk-input-group-input` only (async side-effect import). */
export async function registerPkInputGroupInput(): Promise<void> {
    await import('./components/input-group/pk-input-group-input.js');
}

/** Register `pk-input-group-text` only (async side-effect import). */
export async function registerPkInputGroupText(): Promise<void> {
    await import('./components/input-group/pk-input-group-text.js');
}

/** Register `pk-input-group-textarea` only (async side-effect import). */
export async function registerPkInputGroupTextarea(): Promise<void> {
    await import('./components/input-group/pk-input-group-textarea.js');
}

/** Register `pk-lightswitch` only (async side-effect import). */
export async function registerPkLightswitch(): Promise<void> {
    await import('./components/lightswitch/pk-lightswitch.js');
}

/** Register `pk-option` only (async side-effect import). */
export async function registerPkOption(): Promise<void> {
    await import('./components/select/pk-option.js');
}

/** Register `pk-option-group` only (async side-effect import). */
export async function registerPkOptionGroup(): Promise<void> {
    await import('./components/select/pk-option-group.js');
}

/** Register `pk-popover` only (async side-effect import). */
export async function registerPkPopover(): Promise<void> {
    await import('./components/popover/pk-popover.js');
}

/** Register `pk-popup` only (async side-effect import). */
export async function registerPkPopup(): Promise<void> {
    await import('./components/popup/pk-popup.js');
}

/** Register `pk-radio` only (async side-effect import). */
export async function registerPkRadio(): Promise<void> {
    await import('./components/radio-group/pk-radio.js');
}

/** Register `pk-radio-group` only (async side-effect import). */
export async function registerPkRadioGroup(): Promise<void> {
    await import('./components/radio-group/pk-radio-group.js');
}

/** Register `pk-scroll-area` only (async side-effect import). */
export async function registerPkScrollArea(): Promise<void> {
    await import('./components/scroll-area/pk-scroll-area.js');
}

/** Register `pk-select` only (async side-effect import). */
export async function registerPkSelect(): Promise<void> {
    await import('./components/select/pk-select.js');
}

/** Register `pk-separator` only (async side-effect import). */
export async function registerPkSeparator(): Promise<void> {
    await import('./components/separator/pk-separator.js');
}

/** Register `pk-spinner` only (async side-effect import). */
export async function registerPkSpinner(): Promise<void> {
    await import('./components/spinner/pk-spinner.js');
}

/** Register `pk-status` only (async side-effect import). */
export async function registerPkStatus(): Promise<void> {
    await import('./components/status/pk-status.js');
}

/** Register `pk-tab` only (async side-effect import). */
export async function registerPkTab(): Promise<void> {
    await import('./components/tabs/pk-tab.js');
}

/** Register `pk-tab-heading` only (async side-effect import). */
export async function registerPkTabHeading(): Promise<void> {
    await import('./components/tabs/pk-tab-heading.js');
}

/** Register `pk-tab-panel` only (async side-effect import). */
export async function registerPkTabPanel(): Promise<void> {
    await import('./components/tabs/pk-tab-panel.js');
}

/** Register `pk-tabs` only (async side-effect import). */
export async function registerPkTabs(): Promise<void> {
    await import('./components/tabs/pk-tabs.js');
}

/** Register `pk-textarea` only (async side-effect import). */
export async function registerPkTextarea(): Promise<void> {
    await import('./components/textarea/pk-textarea.js');
}

/** Register `pk-time-picker` only (async side-effect import). */
export async function registerPkTimePicker(): Promise<void> {
    await import('./components/time-picker/pk-time-picker.js');
}

/** Register `pk-tiptap-content` only (async side-effect import). */
export async function registerPkTiptapContent(): Promise<void> {
    await import('./components/tiptap/pk-tiptap-content.js');
}

/** Register `pk-tiptap-editor` only (async side-effect import). */
export async function registerPkTiptapEditor(): Promise<void> {
    await import('./components/tiptap/pk-tiptap-editor.js');
}

/** Register `pk-tiptap-input` only (async side-effect import). */
export async function registerPkTiptapInput(): Promise<void> {
    await import('./components/tiptap/pk-tiptap-input.js');
}

/** Register `pk-toggle` only (async side-effect import). */
export async function registerPkToggle(): Promise<void> {
    await import('./components/toggle/pk-toggle.js');
}

/** Register `pk-toggle-group` only (async side-effect import). */
export async function registerPkToggleGroup(): Promise<void> {
    await import('./components/toggle-group/pk-toggle-group.js');
}

/** Register `pk-tooltip` only (async side-effect import). */
export async function registerPkTooltip(): Promise<void> {
    await import('./components/tooltip/pk-tooltip.js');
}
