import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { BUNDLER_TAG_IMPORT_PATHS } from '../src/component-registry.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const registerPkPath = path.resolve(__dirname, '../src/register-pk.generated.ts');

function tagToRegisterFn(tag: string): string {
    const rest = tag.replace(/^pk-/, '');
    return `registerPk${rest
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('')}`;
}

/**
 * Optional per-tag async helpers (advanced). Preferred DX is family side-effect imports.
 * Kept generated for tooling / playground edge cases — not re-exported from package barrels.
 */
export async function generateRegisterComponents(): Promise<void> {
    const tags = Object.keys(BUNDLER_TAG_IMPORT_PATHS).sort();

    const pkFnEntries = tags
        .map((tag) => {
            const fn = tagToRegisterFn(tag);
            const subpath = BUNDLER_TAG_IMPORT_PATHS[tag];
            return `/** Register \`${tag}\` only (async side-effect import). */
export async function ${fn}(): Promise<void> {
    await import('./${subpath}');
}`;
        })
        .join('\n\n');

    const registerPkContent = `// Generated by scripts/generate-register-components.ts — do not edit.

${pkFnEntries}
`;

    await fs.writeFile(registerPkPath, registerPkContent, 'utf8');

    // Remove the old full-map registrar if present — it pulled every component into the graph.
    const legacyMapPath = path.resolve(__dirname, '../src/register-components.generated.ts');
    await fs.rm(legacyMapPath, { force: true });
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMain) {
    await generateRegisterComponents();
    console.log(`Generated ${registerPkPath} (${Object.keys(BUNDLER_TAG_IMPORT_PATHS).length} tags)`);
}
